{% set name = "pymt_child" %}
{% set data = load_setup_py_data() %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - numpy 1.11.*
    - cython
    - model_metadata
    - child

  run:
    - python
    - setuptools
    - pymt
    - child

test:
  requires:
    - bmi-tester
  imports:
    - pymt_child
  commands:
    - mmd-stage Child .
    - cat child.in
    - child child.in
    - bmi-test pymt_child._child:Child --infile=$(mmd-stage Child .) -vvv

about:
  summary: PyMT plugin for child.
  home: https://github.com/mcflugen/pymt_child
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_child
