language: generic
os:
- osx
- linux
osx_image: xcode6.4
env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7"
  - TRAVIS_PYTHON_VERSION="3.5"
  - TRAVIS_PYTHON_VERSION="3.6"
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda create -n buildit python=$TRAVIS_PYTHON_VERSION
- source activate buildit
- conda install -q conda-build anaconda-client coverage sphinx pytest numpy
script:
- conda build ./recipe -c conda-forge -c csdms-stack --old-build-string
- conda install child model_metadata bmi-tester -c conda-forge -c csdms-stack
- python setup.py install
- bmi-test pymt_child._child:Child --infile=$(mmd-stage Child .) -vvv
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string
  --token=-
